<a href="https://colab.research.google.com/github/prabhjotdakonda/dimensionality-reduction-minor-project-/blob/main/wine_quality_dataset(minor_project).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [232]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [233]:
dfred = pd.read_csv('/content/winequality-red.csv', sep=';')
dfwhite = pd.read_csv('/content/winequality-white.csv', sep=';')

In [234]:
dfred[type]='red'
dfwhite[type]='white'

In [235]:
df=pd.concat([dfred,dfwhite])

In [236]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,<class 'pandas.core.frame.DataFrame'>
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   fixed acidity                          6497 non-null   float64
 1   volatile acidity                       6497 non-null   float64
 2   citric acid                            6497 non-null   float64
 3   residual sugar                         6497 non-null   float64
 4   chlorides                              6497 non-null   float64
 5   free sulfur dioxide                    6497 non-null   float64
 6   total sulfur dioxide                   6497 non-null   float64
 7   density                                6497 non-null   float64
 8   pH                                     6497 non-null   float64
 9   sulphates                              6497 non-null   float64
 10  alcohol                                6497 non-null   float64
 11  quality                                6497 non-null   int64
 12  <class 'pandas.core.frame.DataFrame'>  6497 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 710.6+ KB

In [238]:
#checking the null values
df.isnull().sum()

fixed acidity                            0
volatile acidity                         0
citric acid                              0
residual sugar                           0
chlorides                                0
free sulfur dioxide                      0
total sulfur dioxide                     0
density                                  0
pH                                       0
sulphates                                0
alcohol                                  0
quality                                  0
<class 'pandas.core.frame.DataFrame'>    0
dtype: int64

In [239]:
#checking the duplicated values
df.duplicated().sum()

np.int64(1177)

In [240]:
#removing the duplicated values
df.drop_duplicates(inplace=True)

In [241]:
df.duplicated().sum()

np.int64(0)

In [242]:
df.shape

(5320, 13)

In [243]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5320 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   fixed acidity                          5320 non-null   float64
 1   volatile acidity                       5320 non-null   float64
 2   citric acid                            5320 non-null   float64
 3   residual sugar                         5320 non-null   float64
 4   chlorides                              5320 non-null   float64
 5   free sulfur dioxide                    5320 non-null   float64
 6   total sulfur dioxide                   5320 non-null   float64
 7   density                                5320 non-null   float64
 8   pH                                     5320 non-null   float64
 9   sulphates                              5320 non-null   float64
 10  alcohol                                5320 non-null   float64
 11  quality                                5320 non-null   int64
 12  <class 'pandas.core.frame.DataFrame'>  5320 non-null   object
dtypes: float64(11), int64(1), object(1)
memory usage: 581.9+ KB

In [244]:
df['quality']
#this will be our output column

0       5
1       5
2       5
3       6
5       5
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 5320, dtype: int64

In [245]:
df.columns

Index([                      'fixed acidity',
                          'volatile acidity',
                               'citric acid',
                            'residual sugar',
                                 'chlorides',
                       'free sulfur dioxide',
                      'total sulfur dioxide',
                                   'density',
                                        'pH',
                                 'sulphates',
                                   'alcohol',
                                   'quality',
       <class 'pandas.core.frame.DataFrame'>],
      dtype='object')

In [246]:
df = df.drop(df.columns[-1], axis=1)

In [247]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [248]:
# spliting the data into train test split
from sklearn.model_selection import train_test_split
X=df.drop('quality',axis=1)
y=df['quality']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [249]:
#converting all columns name into strings
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

In [250]:
#standerdizing the data using standard scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [253]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/

In [254]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	sample_data/
	winequality-red.csv
	winequality-white.csv

nothing added to commit but untracked files present (use "git add" to track)

In [257]:
!git config --global user.name "prabhjotdakonda"
!git config --global user.email "prabhjotdakonda@gmail.com"

In [263]:
!git add .

In [265]:

!git commit -m "initial commit"

[master (root-commit) e5f733a] initial commit
 23 files changed, 57558 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2026.05.21/13.26.07.261908.log
 create mode 100644 .config/logs/2026.05.21/13.26.27.601334.log
 create mode 100644 .config/logs/2026.05.21/13.26.42.337595.log
 create mode 100644 .config/logs/2026.05.21/13.26.44.509737.log
 create mode 100644 .config/logs/2026.05.21/13.26.58.743083.log
 create mode 100644 .config/logs/2026.05.21/13.26.59.793897.log
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_data/california_housing_test.csv
 create mode 100644 sample_data/california_housing_train.csv
 create mode 100644 sample_data/mnist_test.csv
 create mode 100644 sample_data/mnist_train_small.csv
 create mode 100644 winequality-red.csv
 create mode 100644 winequality-white.csv

In [266]:
!git remote -v

In [267]:
!git status

On branch master
nothing to commit, working tree clean

In [272]:
!git remote add origin wine_quality_dataset(minor_project).ipynb

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `git remote add origin wine_quality_dataset(minor_project).ipynb'

In [273]:
!git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'origin'

In [275]:
!git log --oneline

e5f733a (HEAD -> master) initial commit

In [276]:
!git branch

* master

In [277]:
!git push -u origin master

fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.